;--------------------------------------------------------------------
; armor: Import Mesh
;--------------------------------------------------------------------
;
; Import the animation file and data files:
;
MESH IMPORT MESH=armor ANIVFILE=\UNREAL\MODELS\aniv36.3D DATAFILE=\UNREAL\MODELS\data36.3D X=0 Y=0 Z=0
MESH ORIGIN MESH=armor X=0 Y=100 Z=200 YAW=0
;
; Assign names to all animation sequences:
;
MESH SEQUENCE MESH=armor SEQ=All    STARTFRAME=0  NUMFRAMES=1
;
;--------------------------------------------------------------------
; armor: Import MeshMap
;--------------------------------------------------------------------
;
TEXTURE IMPORT NAME=Jarmor1 FILE=\UNREAL\MODELS\armor.PCX FAMILY=Skins PALETTE=Jarmor1 FLAGS=2
;
MESHMAP NEW   MESHMAP=armor MESH=armor ; Assign name and mesh to new sprite
MESHMAP SCALE MESHMAP=armor X=0.02 Y=0.02 Z=0.04
;
MESHMAP SETTEXTURE MESHMAP=armor NUM=7 TEXTURE=Jarmor1 ; Apply textures
;
;--------------------------------------------------------------------
; The end
;--------------------------------------------------------------------
 
