;--------------------------------------------------------------------
; clip: Import Mesh
;--------------------------------------------------------------------
;
; Import the animation file and data files:
;
MESH IMPORT MESH=clip ANIVFILE=\UNREAL\MODELS\aniv35.3D DATAFILE=\UNREAL\MODELS\data35.3D X=0 Y=0 Z=0
MESH ORIGIN MESH=clip X=0 Y=100 Z=350 YAW=0
;
; Assign names to all animation sequences:
;
MESH SEQUENCE MESH=clip SEQ=All    STARTFRAME=0  NUMFRAMES=1
;
;--------------------------------------------------------------------
; clip: Import MeshMap
;--------------------------------------------------------------------
;
TEXTURE IMPORT NAME=Jclip1 FILE=\UNREAL\MODELS\clip.PCX FAMILY=Skins PALETTE=Jclip1 FLAGS=2
;
MESHMAP NEW   MESHMAP=clip MESH=clip ; Assign name and mesh to new sprite
MESHMAP SCALE MESHMAP=clip X=0.015 Y=0.015 Z=0.03
;
MESHMAP SETTEXTURE MESHMAP=clip NUM=2 TEXTURE=Jclip1 ; Apply textures
;
;--------------------------------------------------------------------
; The end
;--------------------------------------------------------------------
 
