;--------------------------------------------------------------------
; Gun: Import Mesh
;--------------------------------------------------------------------
;
; Import the animation file and data files:
;
MESH IMPORT MESH=Fireball ANIVFILE=\UNREAL\MODELS\aniv40.3D DATAFILE=\UNREAL\MODELS\data40.3D X=0 Y=0 Z=0
MESH ORIGIN MESH=Fireball X=0 Y=0 Z=0 YAW=64 PITCH=54
;
; Assign names to all animation sequences:
;
MESH SEQUENCE MESH=Fireball SEQ=All  STARTFRAME=0  NUMFRAMES=41
MESH SEQUENCE MESH=Fireball SEQ=Still STARTFRAME=0  NUMFRAMES=1
MESH SEQUENCE MESH=Fireball SEQ=Drop STARTFRAME=1  NUMFRAMES=9
MESH SEQUENCE MESH=Fireball SEQ=Fire STARTFRAME=10  NUMFRAMES=31

;
;--------------------------------------------------------------------
; Fireball: Import MeshMap
;--------------------------------------------------------------------
;
TEXTURE IMPORT NAME=Fireball2 FILE=\UNREAL\MODELS\Fire.PCX FAMILY=Skins PALETTE=Fireball1 ;FLAGS=2 ; if masked
;
MESHMAP NEW   MESHMAP=Fireball MESH=Fireball ; Assign name and mesh to new sprite
MESHMAP SCALE MESHMAP=Fireball X=0.04 Y=0.04 Z=0.08
;
MESHMAP SETTEXTURE MESHMAP=Fireball NUM=0 TEXTURE=Fireball1 ; Apply textures
;
;--------------------------------------------------------------------
; The end
;--------------------------------------------------------------------

 