;--------------------------------------------------------------------
; Gun: Import Mesh
;--------------------------------------------------------------------
;
; Import the animation file and data files:
;
MESH IMPORT MESH=Gun ANIVFILE=\UNREAL\MODELS\ANIV_GUN.3D DATAFILE=\UNREAL\MODELS\DATA_GUN.3D X=0 Y=0 Z=0
MESH ORIGIN MESH=Gun X=0 Y=0 Z=0 YAW=0
;
; Assign names to all animation sequences:
;
MESH SEQUENCE MESH=Gun SEQ=All  STARTFRAME=0  NUMFRAMES=200
;
;--------------------------------------------------------------------
; Gun: Import MeshMap
;--------------------------------------------------------------------
;
TEXTURE IMPORT NAME=Gun1 FILE=\UNREAL\MODELS\GUN1.PCX FAMILY=Skins ;FLAGS=2 ;if masked
TEXTURE IMPORT NAME=Gun2 FILE=\UNREAL\MODELS\GUN2.PCX FAMILY=Skins PALETTE=Gun1 ;FLAGS=2 ; if masked
;
MESHMAP NEW   MESHMAP=Gun MESH=Gun ; Assign name and mesh to new sprite
MESHMAP SCALE MESHMAP=Gun X=0.04 Y=0.04 Z=0.08
;
MESHMAP SETTEXTURE MESHMAP=Gun NUM=4 TEXTURE=Gun1 ; Apply textures
MESHMAP SETTEXTURE MESHMAP=Gun NUM=8 TEXTURE=Gun2 
;
;--------------------------------------------------------------------
; The end
;--------------------------------------------------------------------
 