;--------------------------------------------------------------------
; health: Import Mesh
;--------------------------------------------------------------------
;
; Import the animation file and data files:
;
MESH IMPORT MESH=health ANIVFILE=\UNREAL\MODELS\aniv38.3D DATAFILE=\UNREAL\MODELS\data38.3D X=0 Y=0 Z=0
MESH ORIGIN MESH=health X=0 Y=100 Z=200 YAW=0
;
; Assign names to all animation sequences:
;
MESH SEQUENCE MESH=health SEQ=All    STARTFRAME=0  NUMFRAMES=1
;
;--------------------------------------------------------------------
; health: Import MeshMap
;--------------------------------------------------------------------
;
TEXTURE IMPORT NAME=Jhealth1 FILE=\UNREAL\MODELS\health.PCX FAMILY=Skins PALETTE=Jhealth1 FLAGS=2
;
MESHMAP NEW   MESHMAP=health MESH=health ; Assign name and mesh to new sprite
MESHMAP SCALE MESHMAP=health X=0.03 Y=0.03 Z=0.06
;
MESHMAP SETTEXTURE MESHMAP=health NUM=0 TEXTURE=Jhealth1 ; Apply textures
;
;--------------------------------------------------------------------
; The end
;--------------------------------------------------------------------
 
