;--------------------------------------------------------------------
; light1: Import Mesh
;--------------------------------------------------------------------
;
; Import the animation file and data files:
;
MESH IMPORT MESH=light1 ANIVFILE=\UNREAL\MODELS\aniv30.3D DATAFILE=\UNREAL\MODELS\data30.3D X=0 Y=0 Z=0
MESH ORIGIN MESH=light1 X=0 Y=100 Z=-250 YAW=0
;
; Assign names to all animation sequences:
;
MESH SEQUENCE MESH=light1 SEQ=All    STARTFRAME=0  NUMFRAMES=30
MESH SEQUENCE MESH=light1 SEQ=Still  STARTFRAME=15 NUMFRAMES=1
MESH SEQUENCE MESH=light1 SEQ=Swing  STARTFRAME=0  NUMFRAMES=30
;
;--------------------------------------------------------------------
; light1: Import MeshMap
;--------------------------------------------------------------------
;
TEXTURE IMPORT NAME=Jlight11 FILE=\UNREAL\MODELS\light1.PCX FAMILY=Skins PALETTE=Jlight11 FLAGS=2
;
MESHMAP NEW   MESHMAP=light1 MESH=light1 ; Assign name and mesh to new sprite
MESHMAP SCALE MESHMAP=light1 X=0.05 Y=0.05 Z=0.1
;
MESHMAP SETTEXTURE MESHMAP=light1 NUM=2 TEXTURE=Jlight11 ; Apply textures
;
;--------------------------------------------------------------------
; The end
;--------------------------------------------------------------------
 
