;--------------------------------------------------------------------
; Manta: Import Mesh
;--------------------------------------------------------------------
;
; Import the animation file and data files:
;
MESH IMPORT MESH=Manta ANIVFILE=\UNREAL\MODELS\manta_a.3D DATAFILE=\UNREAL\MODELS\manta_d.3D X=0 Y=0 Z=0
MESH ORIGIN MESH=Manta X=0 Y=-300 Z=100 YAW=64
;
; Assign names to all animation sequences:
;
MESH SEQUENCE MESH=Manta SEQ=All  STARTFRAME=0  NUMFRAMES=30
MESH SEQUENCE MESH=Manta SEQ=Fly  STARTFRAME=0  NUMFRAMES=30
;
;--------------------------------------------------------------------
; Manta: Import MeshMap
;--------------------------------------------------------------------
;
TEXTURE IMPORT NAME=JManta1 FILE=\UNREAL\MODELS\manta.PCX FAMILY=Skins PALETTE=JManta1 FLAGS=2
;
MESHMAP NEW   MESHMAP=Manta MESH=Manta ; Assign name and mesh to new sprite
MESHMAP SCALE MESHMAP=Manta X=0.05 Y=0.05 Z=0.1
;
MESHMAP SETTEXTURE MESHMAP=Manta NUM=2 TEXTURE=JManta1 ; Apply textures
;
;--------------------------------------------------------------------
; The end
;--------------------------------------------------------------------
 
