;--------------------------------------------------------------------
; GunPick: Import Mesh
;--------------------------------------------------------------------
;
; Import the animation file and data files:
;
MESH IMPORT MESH=GunPick ANIVFILE=\UNREAL\MODELS\gunpicka.3D DATAFILE=\UNREAL\MODELS\gunpickd.3D X=0 Y=0 Z=0
MESH ORIGIN MESH=GunPick X=0 Y=0 Z=0 YAW=0
;
; Assign names to all animation sequences:
;
MESH SEQUENCE MESH=GunPick SEQ=All  STARTFRAME=0  NUMFRAMES=1
;
;--------------------------------------------------------------------
; GunPick: Import MeshMap
;--------------------------------------------------------------------
;
TEXTURE IMPORT NAME=GunPick1 FILE=\UNREAL\MODELS\quadhand.PCX FAMILY=Skins PALETTE=GunPick1 ;FLAGS=2 ; if masked
;
MESHMAP NEW   MESHMAP=GunPick MESH=GunPick ; Assign name and mesh to new sprite
MESHMAP SCALE MESHMAP=GunPick X=0.04 Y=0.04 Z=0.08
;
MESHMAP SETTEXTURE MESHMAP=GunPick NUM=4 TEXTURE=GunPick1 ; Apply textures
;
;--------------------------------------------------------------------
; The end
;--------------------------------------------------------------------
 