;--------------------------------------------------------------------
; shells: Import Mesh
;--------------------------------------------------------------------
;
; Import the animation file and data files:
;
MESH IMPORT MESH=shells ANIVFILE=\UNREAL\MODELS\aniv34.3D DATAFILE=\UNREAL\MODELS\data34.3D X=0 Y=0 Z=0
MESH ORIGIN MESH=shells X=0 Y=100 Z=350 YAW=0
;
; Assign names to all animation sequences:
;
MESH SEQUENCE MESH=shells SEQ=All    STARTFRAME=0  NUMFRAMES=1
;
;--------------------------------------------------------------------
; shells: Import MeshMap
;--------------------------------------------------------------------
;
TEXTURE IMPORT NAME=Jshells1 FILE=\UNREAL\MODELS\shells.PCX FAMILY=Skins PALETTE=Jshells1 FLAGS=2
;
MESHMAP NEW   MESHMAP=shells MESH=shells ; Assign name and mesh to new sprite
MESHMAP SCALE MESHMAP=shells X=0.015 Y=0.015 Z=0.03
;
MESHMAP SETTEXTURE MESHMAP=shells NUM=4 TEXTURE=Jshells1 ; Apply textures
;
;--------------------------------------------------------------------
; The end
;--------------------------------------------------------------------
 
